/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemonduels.Grafica;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author babar
 */
public class Grafica extends javax.swing.JFrame {
JPanel panel;
   public ArrayList<JButton> bottone;
        int indice;
    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
      
        int unitaX = this.getWidth()/13;
        int unitaY = this.getHeight()/5;
        int bottoni = unitaX*unitaY+1;
        indice=0;
        bottone=new ArrayList<JButton>();
        panel=new JPanel(new GridLayout(unitaX, unitaY));
        JButton boton =new JButton(String.valueOf(indice));
        panel.add(boton);
        bottone.add(boton);
        indice++;
        panel.updateUI();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
